# Generated by Django 5.0.7 on 2024-08-03 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the sprint", max_length=150),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the sprint"),
                ),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True, help_text="Date of creation of the sprint"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created the sprint",
                        max_length=150,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_sprints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product_owner",
                    models.ForeignKey(
                        help_text="Product owner of the sprint",
                        max_length=150,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_sprints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
