# Generated by Django 5.0.7 on 2024-08-03 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sprints", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the task", max_length=150),
                ),
                ("description", models.TextField(help_text="Description of the task")),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True, help_text="Date of creation of the task"
                    ),
                ),
                (
                    "user_story",
                    models.CharField(
                        blank=True,
                        help_text="User story number",
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created the task",
                        max_length=150,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product_owner",
                    models.ForeignKey(
                        help_text="Product owner of the task",
                        max_length=150,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        max_length=150,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="sprints.sprint",
                    ),
                ),
            ],
        ),
    ]
