# Generated by Django 5.0.7 on 2024-07-24 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sprints", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=150)),
                ("task_title", models.CharField(max_length=150)),
                ("task_info", models.CharField(max_length=450)),
                ("date_posted", models.DateField(auto_now_add=True)),
                ("po_name", models.CharField(max_length=150)),
                ("task_owner", models.CharField(max_length=150)),
                ("user_story", models.CharField(max_length=5)),
                (
                    "sprint_onnected",
                    models.ForeignKey(
                        max_length=150,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="sprints.sprint",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        max_length=150,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
