# Generated by Django 5.1.1 on 2024-09-21 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskEstimation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estimation",
                    models.CharField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "5"),
                            ("5", "8"),
                            ("6", "13"),
                            ("7", "21"),
                        ],
                        max_length=150,
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True, help_text="Date of task estimation"
                    ),
                ),
                (
                    "estimated_by",
                    models.ForeignKey(
                        help_text="User who estimated the task",
                        max_length=150,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        help_text="Who estimated the task",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimations",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "unique_together": {("task", "estimated_by")},
            },
        ),
    ]
