# Generated by Django 5.1.1 on 2024-10-21 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_assigned_users_delete_teammember"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="assigned_users",
        ),
    ]
